### ISSUE TITLE
Linux Build - ARM - Visual Studio is crashing when building the VOID Full IDE

### ISSUE THREAD

**Issue by jcommaret** [voideditor/void#103]
- Node gyp arm has been installed
- Kerberos as well because needed by node gyp
- Docker is working well
- Visualstudio selfhost, python and node version set by asdf, are working perfectly. (I am able to launch the extension)

**Comment by jcommaret** [comment]
To understand what could happen, and check if this is a vscode or void issue, I will build Visual Studio from the open source project.

**Comment by andrewpareles** [comment]
If anyone wants to help out, simply build on Linux! Follow our [Contributing](https://github.com/voideditor/void/blob/main/CONTRIBUTING.md) file, and use Microsoft's [How to Contribute](https://github.com/microsoft/vscode/wiki/How-to-Contribute) guide if you get stuck.

**Comment by jcommaret** [comment]
I was able to have a bit more information on that one. 
I am able to run the `npm run watch` command

Here is the error code. 

<img width="1017" alt="Capture d’écran 2024-10-29 à 13 32 19" src="https://github.com/user-attachments/assets/5812498b-68ca-4483-a628-82b31fd3a9bf">

The VM I am building the Linux ARM version have 4096mo of ram, i limited node to use lower quantity.  

Is it possible to build the full editor without having to do a watch phase ?

**Comment by jcommaret** [comment]
The problem is vscode-native : https://github.com/microsoft/vscode/issues/232535
Here is the link to the vscode issue for follow-up.

**Comment by jcommaret** [comment]
@andrewpareles : I think we will have to manage a rebase using the code-oss 1.96 version. 
there is no watch problem on that build.

**Comment by jcommaret** [comment]
- https://github.com/microsoft/vscode/issues/232953

**Comment by jcommaret** [comment]
As the bug is not on our side, I am closing this issue.
