### ISSUE TITLE
Pass build information to extension

### ISSUE THREAD

**Issue by andrewpareles** [voideditor/void#115]
We want to pass build information into the extension so we can:

- choose whether to display ⌘ or Ctrl
- label that the user is a developer vs in production in metrics
- add a build number for metrics

**Comment by plon-Susk7** [comment]
Hey @andrewpareles , your project seems interesting. I'd love to work on this issue.

**Comment by andrewpareles** [comment]
Hi @plon-Susk7 , sorry I missed this - feel free to hop on this issue!

**Comment by andrewpareles** [comment]
Largely fixed by #172. See metricsService.
