### ISSUE TITLE
Mac OS & Linux : settings.json are not transmitted when using build command

### ISSUE THREAD

**Issue by jcommaret** [voideditor/void#122]
Problem : 
Before the build, I am able to discuss with the void editor using scripts/code.sh 
![beforebuild](https://github.com/user-attachments/assets/4e3b3a5d-eee8-4e90-aefb-e199c27d6e36)

After running the build command, I am not able to do it. It seems package.json settings are not transmitted (void.command.toogleSettings), and settings.json neither. 

![after build](https://github.com/user-attachments/assets/8d0e8a5f-1069-455e-967d-1d496cd33c8a)
![after build 2](https://github.com/user-attachments/assets/10099eae-7910-4a80-a1d4-a0911d2456e7)

Step to reproduce : 
- build the editor from scratch. 

Expected :
- I should be able to input settings, using the "icon" or the command palette.

**Comment by AshDevFr** [comment]
I have the same issue, did you find a workaround to bundle with the settings on MacOS?

**Comment by jcommaret** [comment]
@AshDevFr : not yet, @andrewpareles told me that he was working on that. 
I have a dirty fix in mind. 

Has the settings are stored in Library/void and @andrewpareles know the how this file should look like, maybe he can share us a settings file with options (except the api key) so we can be able to add it afterwards into the Library/void folder.

**Comment by jcommaret** [comment]
@andrewpareles do you have any schedule on this ?

**Comment by jcommaret** [comment]
@andrewpareles i am still investigating this issue, so I am building a virtual MacOS to run in vmware to understand if the latests MacOS versions needs some tweaking, void (full ide) might not have access to the same system ressources than extensions.

**Comment by andrewpareles** [comment]
Apologies for the late reply. I wonder if this has to do with #136? (If it does, it should be an easy fix inside extension.ts). Mac build worked for me the last time I tested it but I'll keep you posted.

**Comment by jcommaret** [comment]
@andrewpareles what is your MacOS version ?
I had the same intuition, this 2 problems looks like they are very related to settings.json.

**Comment by jcommaret** [comment]
@andrewpareles I think you could try to fix extension.ts 

The same problem appears after building the extension on a MacOS Virtual machine running Sonoma. (I used gemini for activating the extension - thanks it's free and no credits are required, can be used worldwide... ) 

![Capture d’écran 2024-11-03 à 12 46 01](https://github.com/user-attachments/assets/f6daf23e-febb-436f-9a4b-673899bf6fee)

So actually I am not able to run the full ide with extension.

**Comment by andrewpareles** [comment]
Does #103 (rebasing) fix this?

**Comment by jcommaret** [comment]
@andrewpareles I wasn't able to Check it right now.

**Comment by jcommaret** [comment]
@andrewpareles :
- I deleted the folder.  
- I recloned the project. 
- I cleaned node.js cache.
- Installed the project. Nothing to do. this doesn't work. 
  
I am not sure on how to update the visual code studio dependency inside this project.  

However, running with script/code.sh is working.

**Comment by jcommaret** [comment]
![Copie d'écran_20241113_161244](https://github.com/user-attachments/assets/d2488003-9a14-40ae-8120-38609e76bd94)

I am having the same problem on Fedora 40 / Asahi

**Comment by jcommaret** [comment]
The extension now doesn't allow me the edit the settings at any place

@andrewpareles : 

-> When full ide build : 

Running scripts/code.sh : 
![Capture d’écran 2024-11-18 à 13 21 55](https://github.com/user-attachments/assets/f6c1b5c0-7032-4d0e-843d-86fa10a7744c)

-> Same problems happens on extension build
