### ISSUE TITLE
Migrate Webviews to Native HTML

### ISSUE THREAD

**Issue by andrewpareles** [voideditor/void#124]
Most of our code for the core functionality of Void runs inside <script /> tags that mount inside a webview iframe.

iframe scripts aren't allowed to call `vscode` functions, so we set up a complicated messaging process to send messages between the iframe script and the main `extension.js` file. 

We'd like to ditch all our webview architecture, and instead mount all of our code inside of VSCode natively. This would require migrating our `/extensions/void` extension to live natively in the editor.

**Comment by jcommaret** [comment]
`postMessage()`, is able to enable communication between iframe and his parent. 
 
 I had to use it for a media website where the cookies disclaimer was in an iframe loaded in overlay, and we have to remember the choice inside the main website.  
 
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage 

That worked great and could be a quick fix before refactoring.

**Comment by andrewpareles** [comment]
Thanks, we already use postMessage()!

**Comment by andrewpareles** [comment]
#119

**Comment by andrewpareles** [comment]
Solved by #139!
