### ISSUE TITLE
max_tokens (max_completion_tokens) not allowed for all configurations of OpenAICompatible

### ISSUE THREAD

**Issue by IDLe-Engineering** [voideditor/void#128]
"object": "error",
"message": "[{'type': 'extra_forbidden', 'loc': ('body', 'max_completion_tokens'), 'msg': 'Extra inputs are not permitted', 'input': 8192}]",
"type": "BadRequestError",
"param": null,
"code": 400

Option necessary to disable max_tokens

**Comment by andrewpareles** [comment]
Added the ability to specify number of tokens manually or leave it blank. 

Just so we know, what provider are you using (which doesn't support max_completion_tokens)?

**Comment by IDLe-Engineering** [comment]
Thanks Andrew! replied in Discord

**Comment by IDLe-Engineering** [comment]
Tested and it works. I am closing the issue
