### ISSUE TITLE
Linux - extension build : cannot find module './util' 

### ISSUE THREAD

**Issue by jcommaret** [voideditor/void#132]
Problem : 
- This looks like there is a missing dependency 

How to reproduce 
- Try build the extension 

Expected : 
- Extension build

![Capture d’écran 2024-10-28 à 14 54 28](https://github.com/user-attachments/assets/15bcdb02-4bb8-4b4e-8906-b8b8317e1afc)

**Comment by andrewpareles** [comment]
`npm run build` inside `/extensions/void` works for me. Can you try reloading node_modules?
