### ISSUE TITLE
Moving the chat box position is disabling the extension

### ISSUE THREAD

**Issue by jcommaret** [voideditor/void#136]
- OS Version : MacOS bêta 15.2 (24C5057p)

Problem : 
- The extension is not activated after moving the chat box. 

How to reproduce : 
- Run scripts/code.sh with the activated extension.  
- Type a message in the chat box
- Move the chat box
- Type a message in the box

Here is a video demo : 
https://github.com/user-attachments/assets/9a3d13bd-b02e-4e3d-95c2-1793387a4d61

Expected : 
I should be able to move the chat window and keeps settings persistent.

**Comment by andrewpareles** [comment]
Fixed!
