### ISSUE TITLE
 Cannot find module extension.js

### ISSUE THREAD

**Issue by tirohia** [voideditor/void#147]
Attempting to build the void extension in vscodium on Mint. I am assuming it should work the same as building with vscode. Happy to for this to be closed and trashed if I've got this fairly basic assumption wrong. I am assuming that the vscode engine version of ^1.92.0 referred to in the extensions package.json should mean that version 1.95.1 of codium should work. I could be entirely wrong on that though. 

After git clone, I'm opening the extensions/void directory in a new code workspace. I'm do npm install from a terminal in that workspace, that works - though there are a bunch of warnings they mostly look to be concerned with linting. I do very little with node, so I have no idea if those are relevant or not, I suspect not, but I have attached them in a file. 

[npmInstallWarnings.txt](https://github.com/user-attachments/files/17760182/npmInstallWarnings.txt)

The npm build I can do through the run/debug interface, or the terminal. This part also works, generates this:
```
> void@0.0.1 build
> rimraf dist && node build/build.js

converting  src/webviews/sidebar/index.tsx  -->  dist/webviews/sidebar/index.js
converting  src/webviews/ctrlk/index.tsx  -->  dist/webviews/ctrlk/index.js
converting  src/webviews/diffline/index.tsx  -->  dist/webviews/diffline/index.js
converting  src/webviews/styles.css  -->  dist/webviews/styles.css
```
Which ever way I do the build, running the extension starts a new instance of code, but generates this error, with the void chat never fully resolving, i.e. it hangs. 

```
Activating extension 'void.void' failed: Cannot find module '/home/ben/workspace/void/extensions/void/out/extension/extension.js'
Require stack:
- /app/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js.
```

Which is remarkably similar to #118, which has apparently been fixed by #119, with the proviso that that is referring to Mac rather than Linux. The git clone is fresh, if the fix for #119 has been merged into main I should have it. 

Running Linux Mint 21.3 Virginia
Kernel: 5.15.0-125-generic x86_64
VSCodium 1.95.1
Nodejs: 20.18

Happy to go digging for any else that might be relevant, though the chances of me being able to find things without guidance as to where and how are 50:50. 

Thanks.
Ben.

**Comment by andrewpareles** [comment]
Hi Ben, sorry for the Node build pain. I'm migrating the codebase away from an extension right now so that we don't have to deal with the pains of building an extension. 

Running `npm run compile` (or pressing F5) in the extension folder should hopefully fix your problem... you can at least see if an out/ folder is being generated after running the command.

If you want to play around with the new version I'm about to pull, my changes are all on the branch `actual-editor-insets`. To run that branch you just need to run `node build.js` inside `src/vs/workbench/contrib/void/browser/react` (and have tsup installed).

Let me know if you have any issues with either of these.

**Comment by tirohia** [comment]
All good. 

`npm run compile` does indeed start a new session, with the void chat extension enabled. 

After stopping that, re-running with F5 also starts a new session with the extension enabled, so whatever the` npm run compile` does, it fixes the problem. Previously F5 was starting a new session with the same "Activating extension 'void.void' failed error. 

As a general heads up, I'm assuming it's beyond the scope of the current work, but from that new session, when I open a workspace on a remote host, the extension disappears. I'm assuming that there's something that needs to happen for the extension to be installed on the remote host that doesn't work (or is at least a little beyond me) when building the extension from scratch. 

Cheers. 
Ben.

**Comment by andrewpareles** [comment]
We should revisit the remote host issue when we've migrated the code to live natively - I'll leave this issue open for now. Thanks for the report!

**Comment by andrewpareles** [comment]
Hey @tirohia, we just pushed some changes. Let me know if you still have any issues building on Mint.

**Comment by andrewpareles** [comment]
Void is no longer an extension, so this error is old. Please let us know if you have trouble building the new version of Void!

**Comment by boltomli** [comment]
`node build.js` inside `src/vs/workbench/contrib/void/browser/react` is still necessary on latest main branch

**Comment by andrewpareles** [comment]
I think `npm run buildreact` or `npm run watchreact` works for this, no?
