### ISSUE TITLE
Update diffs on changes

### ISSUE THREAD

**Issue by andrewpareles** [voideditor/void#15]
When the user presses "Accept" or "Reject" on a diff, all of the diffs below should be updated, because they are now on different line numbers.

**Comment by liamstamper** [comment]
and can i have more info

**Comment by avinpy-255** [comment]
## Approved and Reject Section
### Screencast
[Screencast from 2024-09-20 13-04-23.webm](https://github.com/user-attachments/assets/50b877d9-d5c2-4aca-b019-85b2835f1439)

After selecting a section of the code and pressing `Ctrl + L`, the following interface appears.
![Screenshot of the approved and reject section](https://github.com/user-attachments/assets/09c48acb-da46-4ce6-8be0-4ca45bc9b33e)

**Comment by EliphazBouye** [comment]
@liamstamper just do it and send PR

**Comment by andrewpareles** [comment]
Did you push any code? I'm not sure what this video is showing.

**Comment by andrewpareles** [comment]
Thanks @mathewpareles.
