### ISSUE TITLE
 Error building dev container image 

### ISSUE THREAD

**Issue by clstaudt** [voideditor/void#151]
When attempting to build a dev container image for the project, an error occurred while trying to load metadata for the `dev_container_feature_content_temp` image. 

The relevant part of the error message is:
```
> [internal] load metadata for docker.io/library/dev_container_feature_content_temp:latest:
------
Dockerfile-with-features:20
--------------------
  20 | >>> FROM dev_container_feature_content_temp as dev_containers_feature_content_source
--------------------
error: failed to solve: dev_container_feature_content_temp: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

It appears the `dev_container_feature_content_temp` image could not be pulled, either because the repository does not exist or due to insufficient authorization.

This occurred when trying to build the container image defined in the `.devcontainer/devcontainer.json` file which references some additional dev container features.

To Reproduce:
1. Open the project in VS Code 
2. Attempt to re-build and reopen in container

Additional Context:
- VS Code version: 1.95.2 
- Dev Containers extension version: 0.388.0
- Operating System: macOS arm64
- Docker Desktop version: 4.5.0

**Comment by andrewpareles** [comment]
Hi Chris, thanks for the issue. This is strange as it doesn't look like any of our devcontainer files differ from Microsoft's. I saw that you posted #157, are you still having trouble with this devcontainer issue, or did you find a workaround?

**Comment by clstaudt** [comment]
Hi @andrewpareles,  I am still having issues building the project. Since I am not a JS developer, I don't have much hope in finding a workaround. Just checking out the project with great intereste, trying to follow the build instructions and reporting that it didn't work on my machine.

**Comment by andrewpareles** [comment]
Thanks @clstaudt. Responded to your post #160.
