### ISSUE TITLE
Error running `node ./build.js` command due to `tailwind.config.js` module format issue

### ISSUE THREAD

**Issue by clstaudt** [voideditor/void#157]
I encountered an error when running the `node ./build.js` command in my project. The error message indicates that there is an issue with the `tailwind.config.js` file's module format.

Error Message:
```
Error: Error: Command failed: tailwindcss -i src2/styles.css --prefix "prefix-" 

file:///path/to/project/src/vs/workbench/contrib/void/browser/react/tailwind.config.js:2
module.exports = {
^

ReferenceError: module is not defined
    at file:///path/to/project/src/vs/workbench/contrib/void/browser/react/tailwind.config.js:2:1
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5) {
  status: 1,
  signal: null,
}
```

It seems that the `tailwind.config.js` file is using `module.exports`, which is not supported in an ES module context.

Steps to Reproduce:
1. Run `npm install` in the project root directory
2. Navigate to `./src/vs/workbench/contrib/void/browser/react/` directory
3. Run the command `node ./build.js`

Expected Behavior:
The `node ./build.js` command should execute successfully without any errors related to the `tailwind.config.js` file.

Actual Behavior:
The command fails with the error message mentioned above, indicating that `module` is not defined in the `tailwind.config.js` file.

Environment:
- Node.js version: v23.3.0
- Operating System: macOS

I would appreciate any assistance or guidance on resolving this issue. Please let me know if you need any further information or clarification.

Thank you for your help!

**Comment by Invernomut0** [comment]
Same error here (Mac M1):

Node Version: v23.1.0
Mac OS: 15.1.1

[error.log](https://github.com/user-attachments/files/17908173/error.log)

thanks!

**Comment by andrewpareles** [comment]
Can you try node version 20.16.0?

**Comment by clstaudt** [comment]
After downgrading node, I seem to be one step further, but still cannot run the editor.


```
cls@clsm3ba-2 ~/D/W/R/F/v/s/v/w/c/v/b/react (main)> node ./build.js                                                                                                                                             (base) 
cls@clsm3ba-2 ~/D/W/R/F/v/s/v/w/c/v/b/react (main)> npm run watch                                                                                                                                               (base) 
npm error Missing script: "watch"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /Users/cls/.npm/_logs/2024-11-26T14_07_29_839Z-debug-0.log
```

**Comment by clstaudt** [comment]
@andrewpareles  This worked, I can now run proceed to the next steps.

However, I am experiencing [another issue](https://github.com/voideditor/void/issues/160) that keeps me from starting the editor.

**Comment by Invernomut0** [comment]
@clstaudt go to the main directory and launch npm run watch

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/8d51c9b5-6795-424b-bed2-8aede713c9a1">

**Comment by clstaudt** [comment]
@Invernomut0  `npm watch` is running without errors.

**Comment by andrewpareles** [comment]
@Invernomut0 Great! Let me know if you have any other issues. If you're interested in contributing, we mostly need to build nice UI right now 🙂 a lot of our UI is now slightly broken due to the migration.

@clstaudt I'm moving this issue to #160, and closing #151
