### ISSUE TITLE
Clear selection on ctrl+L

### ISSUE THREAD

**Issue by andrewpareles** [voideditor/void#16]
Right now, the history grows indefinitely. It should instead be cleared when the user presses ctrl+L (and recorded somewhere). We'll add a UI for viewing past history items later.

**Comment by DineshSolanki** [comment]
can you explain it a bit, like should each <kbd>ctrl + L</kbd> be made into individual chat sessions, that can be stored and cleared?

**Comment by mathewpareles** [comment]
Exactly, when the user presses `ctrl + L`, the current session (all of the chats inside of the sidebar) should be cleared and saved for later.

**Comment by gowmss** [comment]
define more?
.
