### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by andrewpareles** [voideditor/void#162]
We should make sure our docs are all up to date. 

If you see any docs that are outdated (e.g. #161), feel free to update.

**Comment by jcommaret** [comment]
- What is the Void's blog post guide link ?
- At the end of VOID_USEFULL_LINKS, there is a section with outdated info related to vscode, should we remove it ?
- Does the VOID_USEFULL_LINKS still usefull ?

Git is keeping information anyway.
