### ISSUE TITLE
[Templates]AI rules

### ISSUE THREAD

**Issue by jcommaret** [voideditor/void#163]
AI rules is a template who encapsulates all the messages send to API
If you want the AI to always respond in a specified language, you should be allowed to prompt it once. 

Some IA allows natively theses settings, at model levels, others ones doesn't include them. 

As theses settings are not consistent over all AI, maybe adding a template to "normalise" the answers, could be nice. 

This settings is coming from cursor, and this is a really good idea to implement. 

![Capture d’écran 2024-11-30 à 17 01 13](https://github.com/user-attachments/assets/c10d3973-8f41-4b65-9375-578bfd2b0154)

**Comment by andrewpareles** [comment]
I'm going to merge #116 soon - I think this should resolve this issue!

**Comment by andrewpareles** [comment]
Placeholder template:`Do not add/remove/modify code spacing. Write comments in lowercase. Always respond in French.`
