### ISSUE TITLE
[Question - Guide]How to develop an extension for VOID ?

### ISSUE THREAD

**Issue by jcommaret** [voideditor/void#164]
Is there any known guide on how to develop an extension for VOID ? 
I'd like to add an AI model into the model selection (MISTRAL) 

Allowing to the Mistral API Guide, I should be able to use OpenAPI AI spec

But there is also a lot more things I might be able to do. 

How to implement a new AI model and its own specificity ?

**Comment by andrewpareles** [comment]
Great question - is there more you'd like to configure in the openaiCompatible setting than the options we currently offer?

**Comment by andrewpareles** [comment]
We'd like to eventually add an extensions API for models and for UI (e.g. the streaming UI we built with accept|reject sections). Adding Mistral should be possible with Void as-is, though.

**Comment by eamodio** [comment]
Would you leverage the new AI extension apis that VS Code supports for AI models?

**Comment by jcommaret** [comment]
@andrewpareles : 

Actually, void is a vscode fork, so allowing an extension to change things, inside the code, is like the same problem you had :  you had to allow code changes from ai.  

The main void goal is to develop an opensource marketplace for AI builder, This is really an ambitious problematic, because for each extension loaded, it is like building a new void fork for each person. Void Startup problem solved. 

All the languages models actually in the void editor are actually American, and you are advertising theses models by naming them. 

I want to be able to add an extension for mistral.   

I actually to build the Mistral - Codestral implementation - extension for void - this is a French startup who is trying to be as French as possible, so no compromise will be possible. 

Mistral is fighting against Google, OpenAI, and other LLMs companies. 

This is actually possible to duplicate the openAPI spec, and add Mistral like the gemini implementations was done. 
But the model is also capable of doing a lot more stuff. 
But we all know that every person in the world, will want to build is own fined tuned language model in a nearby future. 

So let's build the editor who can support it ;)

**Comment by andrewpareles** [comment]
> Would you leverage the new AI extension apis that VS Code supports for AI models?

I don't think so, at least for now. We've been building our own UI and didn't love the feel of vscode's api when we played around with it. Are there specific pieces of UI you think we should look into?

**Comment by andrewpareles** [comment]
> Would you leverage the new AI extension apis that VS Code supports for AI models?

Thanks for asking, @eamodio - big fan of GitLens. Vscode's extension api felt a little foreign when we played around with it, so I'm not sure if we'll use it in the near term. Are there specific pieces of UI you think we should look into?

**Comment by jcommaret** [comment]
> Great question - is there more you'd like to configure in the openaiCompatible setting than the options we currently offer?

@andrewpareles : let me try to build the Mistral extension. I donc like to have an "openAI" compatible settings, because we might have multiple openAi compatibles "providers". That we might want to switch regarding the complexity of the question, the API Cost, an even more. 

Some settings should be persistent, and duplicable.

**Comment by andrewpareles** [comment]
It's important to have an openai-compatible provider, but we might just add it under openai by adding a baseUrl option. Happy to review Mistral when you're done!
