### ISSUE TITLE
[UI Improvement]Quick model switching

### ISSUE THREAD

**Issue by jcommaret** [voideditor/void#170]
When you use many LLM, you might want to switch quickly between them. 
-> 1 click is quicker than 3 

Another well known editor used this solution : 
![Capture d’écran 2024-12-07 à 13 13 53](https://github.com/user-attachments/assets/4603de90-dde4-4e28-8634-e560a5a2327f)

This is a quite nice solution.

**Comment by andrewpareles** [comment]
See #172
