### ISSUE TITLE
Bundle errors

### ISSUE THREAD

**Issue by andrewpareles** [voideditor/void#173]
Multiple people have reported a blank screen after bundling the Void executable. 

If this is an error on Void’s end, it‘s probably due to import changes that we introduced (we are directly importing ‘openai’ and other packages in electron-main). It could alternatively just be caused by vscode’s finicky bundler or cache errors, but it seems like a recurring issue.

**Comment by datosh** [comment]
I also tried to build (works fine) and bundle (only shows default Electron app screen) Void, yesterday, based on main@296cd1b4. 
Happy to test a new version or provide more details from my side!

**Comment by andrewpareles** [comment]
Thanks @datosh! Just want to make sure, did you run `npm run gulp vscode-darwin-arm64`? If so, can you run one of these 3 commands instead?
- `npm run gulp vscode-darwin-linux-ia32`
- `npm run gulp vscode-darwin-linux-x64`
- `npm run gulp vscode-darwin-linux-arm`

**Comment by andrewpareles** [comment]
Actually, it looks like a dependency issue - I'm working on fixing this now!

**Comment by andrewpareles** [comment]
Fixed on `model-selection` branch. The issue was that dependencies like 'openai' were devDependencies in package.json, not normal ones.

**Comment by andrewpareles** [comment]
Fixed by #172. Please report if you still face any issues!
