### ISSUE TITLE
Missing Package Errors When Building the Project

### ISSUE THREAD

**Issue by vys69** [voideditor/void#21]
# Missing Package Errors When Building the Project
## System Info:
```
OS: Windows 10, Version 22H2 (Build 19045.4780)
GPU: Zotac GTX 1660
RAM: 48GB DDR4
CPU: Ryzen 5 2600
```
### Clone the repository:
```bash
git clone <project-link>.git
cd void
```
### Install deps:
```bash
yarn install
```
### Error output
```bash
yarn run v1.22.22
warning ..\package.json: No license field
$ deemon yarn watch-client
...
Error: Cannot find module 'gulp-merge-json'
...
Error: Cannot find module 'ternary-stream'
...
...
[deemon] Build daemon exited.
Done in 2.78s.
```
### More info:

I assume ternary stream and gulp...-json aren't my only errors, but these are just what I could get to show. I've tried a few re installs in case I missed a few steps, but this is pretty consistent for me.

I even installed VSCode for this 😔

**Comment by qodesmith** [comment]
I bet you it's a Node version mismatch. This project currently uses [Node 20.14.0](https://github.com/voideditor/void/blob/main/.nvmrc). I know that `yarn install` can fail if there are Node version mismatches. You can use [fnm](https://github.com/Schniz/fnm) to manage multiple versions of Node. After you install fnm, just type `fnm use` in this project's directory and try `yarn install` again.

**Comment by andrewpareles** [comment]
Are you using a dev container?

**Comment by vys69** [comment]
> I bet you it's a Node version mismatch. This project currently uses [Node 20.14.0](https://github.com/voideditor/void/blob/main/.nvmrc). I know that `yarn install` can fail if there are Node version mismatches. You can use [fnm](https://github.com/Schniz/fnm) to manage multiple versions of Node. After you install fnm, just type `fnm use` in this project's directory and try `yarn install` again.

This worked for me, thank you, Qodesmith 🙌
