### ISSUE TITLE
[Improvement] Homogeneous SDK for all AI model providers via Vercel ai sdk

### ISSUE THREAD

**Issue by pradhyumna85** [voideditor/void#27]
**Current LLM calling implementations:** https://github.com/voideditor/void/blob/main/extensions%2Fvoid%2Fsrc%2Fcommon%2FsendLLMMessage.ts

## Proposal
I think we should replace all the existing model calling interfaces with a single homogeneous API for all popular providers using **Vercel AI SDK**: https://sdk.vercel.ai/docs/introduction

## benefits
- supporting more models from different model providers (including ollama)
- Decreases void's workload and responsibility for maintaining and updating each model provider's sdk
- integration of any new model provider would be straight forward if available in Vercel ai SDK

**Comment by okxiaoliang4** [comment]
I am working for this. PR going soon

**Comment by andrewpareles** [comment]
Closing; further work will take place in #41
