### ISSUE TITLE
Errors building from source.

### ISSUE THREAD

**Issue by twilwa** [voideditor/void#35]
Hi, I'm trying to get the IDE + extension built as described in CONTRIBUTING.md. I can get the IDE itself to run, but when it starts up, I encounter the following:

Activating extension 'undefined_publisher.void' failed: Cannot find module '/home/anon/repos/void/extensions/void/out/extension.js'
Require stack:
- /home/anon/repos/void/out/vs/loader.js
- /home/anon/repos/void/out/bootstrap-amd.js
- /home/anon/repos/void/out/bootstrap-fork.js.

and the extension seems to simply load forever. I'll try to install a normal installation of vscode and see if I can get just the extension up for further testing.

**Comment by twilwa** [comment]
Update: turns out I just needed to follow the directions exactly. Getting the IDE open, then ctrl+shift+b, then reload window seems to have gotten me up and running, i'll go ahead and close with comment for now. However, if there are any usage instructions, I'd be keen to play around with it a bit -- so far all I can see is the ctrl+L to chat with a file i have open.

**Comment by heyan6666** [comment]
hi

**Comment by mathewpareles** [comment]
> edit: after checking the landing page, i did notice that i ought to be able to ctrl+k, but i error out with 'command 'void.ctrl+k' not found. not sure if it's just not implemented yet, but i can open a new issue if it's intended to be functional.

See https://github.com/voideditor/void/issues/11.
