### ISSUE TITLE
Search Old Codes

### ISSUE THREAD

**Issue by never2average** [voideditor/void#45]
We literally have a slack channel called #good-codes where we end up sharing/saving code snippets. I would like to add 2 commands into this for saving and searching old codebases.

The architecture would be:
1. Write to my/org github gist whenever I save a snippet 
2. generate some docstrings for it automatically
3. Embed the doc string
4. and have a search feature.

Would work with 2 additional shortcuts Cmd+option+S and command+space

Replaces bulky software like pieces.app

**Comment by andrewpareles** [comment]
Are you proposing a native integration with slack for searching code snippets?

**Comment by mathewpareles** [comment]
Please repost with a clearer title and description. It seems like you are just proposing the ability to search over a codebase.
