### ISSUE TITLE
Build error no such file or directory markdown-language-features/preview-src/src

### ISSUE THREAD

**Issue by ywiyogo** [voideditor/void#48]
After preparing everything by following the instructions in CONTRIBUTING.md, running `npm run watch` return this error:
```
[watch-extensions] [20:45:55] 'watch-extensions' errored after 949 ms
[watch-extensions] [20:45:55] Error: ENOENT: no such file or directory, scandir '/home/x/void/extensions/markdown-language-features/preview-src/src'
ERROR: "watch-extensions" exited with 1.
```

**Comment by Abraham599** [comment]
@ywiyogo are you using Windows 11 OS too ?

**Comment by ywiyogo** [comment]
> @ywiyogo are you using Windows 11 OS too ?

`/home/x/void/` is a folder structure of Linux, not Windows 11.

**Comment by andrewpareles** [comment]
Any luck with the latest version?

**Comment by andrewpareles** [comment]
Can you try again with the latest version?

**Comment by andrewpareles** [comment]
@ywiyogo Can you try again with the latest branch?

**Comment by ywiyogo** [comment]
> @ywiyogo Can you try again with the latest branch?

No error anymore. It works @andrewpareles!
