### ISSUE TITLE
Missing script: "build"

### ISSUE THREAD

**Issue by Ric-Lan** [voideditor/void#49]
PS C:\Users\Ric\.vscode\extensions\void> npm run build
npm error Missing script: "build"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: C:\Users\Ric\AppData\Local\npm-cache\_logs\2024-09-21T17_29_50_327Z-debug-0.log

package.json is exist, I don't know what part need to do.
[2024-09-21T17_27_10_990Z-debug-0.log](https://github.com/user-attachments/files/17085173/2024-09-21T17_27_10_990Z-debug-0.log)

**Comment by ydhnwb** [comment]
This doesn't happen on my machine. Make sure you are on correct directory which is inside this repository folder e.g `void/extensions/void`, make sure there is a package.json there and run your npm run build.


I suspect that your directory "Ric.vscode" is not a cloned version of this repository

**Comment by andrewpareles** [comment]
Please run `npm run build` inside `extensions/void`.
