### ISSUE TITLE
Create a native diff component

### ISSUE THREAD

**Issue by mathewpareles** [voideditor/void#50]
When the user applies changes to a file, Void will highlight all of the additions in green. Here's an example:

https://github.com/user-attachments/assets/3f2e6ee9-d64f-4312-b338-fe02d32bfff2

However, Void should also display the parts of the file that were deleted. Here's a mock-up of what we want this to look like for the above example. The diff should include both the insertions (green) and deletions (red):

![expected-diff](https://github.com/user-attachments/assets/d3d64ab9-6533-4426-b958-74ec6009f212)

**Task: Show diffs as above.** This requires creating a new provider for diffs `diffProvider`, and using it in Void's VS Code extension.

Constraints:
1. When a diff is displayed, it should not cause a syntax error in the file.
2. When the user selects everything in the file (`ctrl + a`), the deletion parts of diffs should not be included in their selection.

**Comment by andrewpareles** [comment]
#119 starts this
