### ISSUE TITLE
Not getting LLM response from the Sidebar component

### ISSUE THREAD

**Issue by Abraham599** [voideditor/void#58]
The steps I took to run the extension :-

1. forked and cloned the repo of void (https://github.com/voideditor/void)
2. Opened the extensions/void as a Window in VS code
3. npm install
4. npm run build
5. pressed f5 to run the extension
6. create a new api key from anthropic's console and then copied it
7. pressed (CTRL+,) to open the Settings and then typed Void
8. Set the api key for anthropic key-value pair in the environment variable for both User and Workspace
9. pressed (CTRL+L) to open the Sidebar then again (CTRL+L) to highlight a line of code to specify some changes
10. for this case, I just asked the LLM to add a new line below the highlighted line of code. After which it simply doesn't return me a response for a long time even though after clicking on the button the text of the button changes to "Stop".

Checkout this image

![image](https://github.com/user-attachments/assets/2509669c-95f1-417b-aacc-1c2b42a6006b)

**Comment by mathewpareles** [comment]
Seems to be a problem on Windows 11 systems. We should look into what's causing this.

**Comment by khy-sothavirak** [comment]
If you have not subscribe to any plan, you would not be able to call anthropic api. Would be useful to see the error logs when it is attempting to call the API, currently we it just got stuck and not sure what is happening in the background.

**Comment by Abraham599** [comment]
@khy-sothavirak I don't get what you are saying. What subscription plan are you talk about ? There is absolutety no necessity for the contributors to subscribe to a plan in order to contribute to Void. 

Here is my debug console when I run the extension and prompt something. There are literally no errors.

![image](https://github.com/user-attachments/assets/52e7fc8b-b3e5-4d1b-8f24-9ffe751343d9)

**Comment by khy-sothavirak** [comment]
Subscription to the Anthropic, you need to have credit to call their APIs. Btw... from above console, the apikey is empty, is that expected?

**Comment by Abraham599** [comment]
I already have the credits. The api key is set, I have blurred it with a black strip in the image.

**Comment by andrewpareles** [comment]
We added error handling and updated Settings, so this should be fixed. @Abraham599 if this continues to be a problem, DM me or open up a new issue.
