### ISSUE TITLE
Unable to set API

### ISSUE THREAD

**Issue by Cassiano2d** [voideditor/void#68]
When I type "void" in search all I can find is Chat: Focus on void view.
![image](https://github.com/user-attachments/assets/f8527ac9-a459-4592-b90a-617040018512)

**Comment by Abraham599** [comment]
Please follow the CONTRIBUTING.md. You have to press (CTRL+,) to open the Settings then you will have to type in "Void".

**Comment by ubergarm** [comment]
You can edit three lines of code to get it working with any local LLM API endpoint until they sort out ollama and other provider details:

https://github.com/voideditor/void/issues/74#issuecomment-2379722341
