### ISSUE TITLE
How can I convert an OpenAI endpoint to a local VLLM endpoint?

### ISSUE THREAD

**Issue by ShikangPang** [voideditor/void#69]
I deployed the vllm model locally and tried to connect using the void extension, but I can't initiate a conversation. What should I do?

**Comment by andrewpareles** [comment]
We need more details - can you give a few screenshots of what you tried to do?

**Comment by cppcloud** [comment]
Whether it is possible to consider adding an OpenAI-compatible API, adding something like OpenAI_base_url, and being able to use https://xxxx.com/v1.

**Comment by PSKong** [comment]
![image](https://github.com/user-attachments/assets/24068472-db90-41de-8e41-4881904dc828)
 Just like this, I am trying to connect to a local model by modifying the endpoint url and the model.

**Comment by andrewpareles** [comment]
@ShikangPang let us know if it's working now!

**Comment by ShikangPang** [comment]
I can use openaiCompatible option normally。
