### ISSUE TITLE
Code Linting Issue: Implementing Prettier for Code Consistency

### ISSUE THREAD

**Issue by SOUMITRO-SAHA** [voideditor/void#71]
Code Linting Issue: Implementing Prettier for Consistency

#### Issue Description:

Currently, the project lacks any form of automated linting or formatting, which allows inconsistent code styles, poor readability, and potential errors to be introduced into the codebase. Without a proper linting setup, there is no enforcement of coding standards, which can result in varying styles across different parts of the project.

**Problems before implementing linting and Prettier:**

- No linting or formatting rules in place, allowing inconsistent code styles.
- Developers could commit code without a unified format, leading to decreased readability and maintainability.
- Lack of automated checks meant that style violations could easily go unnoticed.

**Comment by andrewpareles** [comment]
Closing; will continue work in the PR #72.
