### ISSUE TITLE
How to use this Api -- Ollama

### ISSUE THREAD

**Issue by Cynric92** [voideditor/void#74]
I don't know how to configure this place,I want to use my Ollama.
![image](https://github.com/user-attachments/assets/03f6c433-2fde-4e1b-b45e-59ff3a75e2f8)

**Comment by ubergarm** [comment]
Seems similar to #68

**Comment by ubergarm** [comment]
@Cynric92 doesn't seem like they have implemented it yet see the code here:

https://github.com/voideditor/void/blob/main/extensions/void/src/common/sendLLMMessage.ts#L22-L24

It may be possible to fix their limited demo code to get it working with a local OpenAPI compatible endpoint such as `llama-server` or `aphrodite-enging`. 

I'll try to make a small patch to the extension, compile it, run it with normal VSCode, and see if I can get it to do anything. Right now it is basically broken to me as a local LLM user afaict.
