### ISSUE TITLE
No Code Highlighting in Sidebar Response

### ISSUE THREAD

**Issue by SOUMITRO-SAHA** [voideditor/void#76]
# Issue: No Code Highlighting in Sidebar Response

Description:
In the sidebar, when displaying code snippets, there is no syntax highlighting being applied. The expected behavior is that code blocks should be highlighted according to the selected programming language and theme. Currently, code appears as plain text, making it harder to distinguish between syntax elements like keywords, variables, and comments.

![image](https://github.com/user-attachments/assets/fd4c260e-b528-4041-81e0-2829f0821827)

**Comment by kalil0321** [comment]
Hi, can I work on this?

**Comment by Aryann15** [comment]
hey @andrewpareles can I work on this?

**Comment by andrewpareles** [comment]
@Aryann15 go for it!

**Comment by andrewpareles** [comment]
Some progress has been made here, but ideally we'd use Monaco editor. See https://github.com/voideditor/void/pull/77#issuecomment-2406719595
