### ISSUE TITLE
There is an error when Building the full IDE : Error parsing certificate:

### ISSUE THREAD

**Issue by RoyLR** [voideditor/void#78]
mac os
There is an error when Building the full IDE : 
[92031:0930/092115.126056:ERROR:trust_store_mac.cc(750)] Error parsing certificate:
ERROR: Failed parsing extensions

**Comment by jcommaret** [comment]
Do you have an apple developer account ?

**Comment by jcommaret** [comment]
@RoyLR : can you give us more insight on the machine you are building ? 
- Architecture : arm or intel ?
- MacOS : version ?
- Xcode : version ?
- Developer account ? yes or no ?
If we can't reproduce it, we won't be able to fix it.

**Comment by andrewpareles** [comment]
Not enough info. Open a new issue to give more context.
