### ISSUE TITLE
chore - separate build process by machine type for the full IDE

### ISSUE THREAD

**Issue by jcommaret** [voideditor/void#85]
**Mac OS :** 
1. `npm install`
2. On MacOs `Command+Shift+B` to start the build process - this can take some time. If you're not using VS Code, run `npm run watch` instead. (maybe removing vs code command will streamline the process because it will be one generic command not related to environnement) 
3. Open terminal and run `chmod +x scripts/code.sh`
4. Run `scripts/code.sh` in your terminal.

Using only terminal tou have to do 
- `npm install`
- `npm run watch`
- `chmod +x scripts/code.sh`
- drag and drop `code.sh` in your terminal and hit enter

then  
- `npm run gulp vscode-darwin-arm64` assuming you are building for macOS silicon
- `npm run gulp vscode-darwin-x64` assuming you are building for Intel

**Windows :** 
-> Use `CTRL+Shift+B` instead of `Command+Shift+B` 

**Linux-arm :** 
-> I have no idea yet, but I will try when MacOS ARM will work on my machine, I can easily run a debian. 

I think we should remove [specific editor and keyboard shortcut abstraction] and let the terminal do the job.

**Comment by jcommaret** [comment]
PR : https://github.com/voideditor/void/pull/114 fix this for Mac OS.

**Comment by andrewpareles** [comment]
Also see #119

**Comment by andrewpareles** [comment]
What do you think about https://github.com/voideditor/void/blob/main/CONTRIBUTING.md ?

**Comment by andrewpareles** [comment]
Solved with the new contributing file https://github.com/voideditor/void/blob/main/CONTRIBUTING.md

We still need to get a Linux build going.
