### ISSUE TITLE
Use Ollama API to start the right model

### ISSUE THREAD

**Issue by jcommaret** [voideditor/void#89]

**Comment by andrewpareles** [comment]
When the user changes the Ollama model, we should communicate with the Ollama API to actually change the model

**Comment by andrewpareles** [comment]
For now, we just let the user pick a model through Ollama (and removed the model selection from Void)

**Comment by PRANJALRANA11** [comment]
@andrewpareles can i look into this

**Comment by andrewpareles** [comment]
> @andrewpareles can i look into this

Definitely! Just submit a PR when you're done :)

**Comment by Madhav160804** [comment]
Can you please clarify the requirements please, should we use the ollama api to get what are models that are installed and only display those models to select from 
OR
when user selects a model which is not present on the system so just better error handling to display that the model doesn't exist ?

**Comment by jcommaret** [comment]
I think starting with launching Ollama and show installed model and select them will be ok. 

Installing ollama local model from void ans selecting them is the absolute goal I think.

**Comment by andrewpareles** [comment]
This issue is still open, because ideally we'd let users pick a model straight from inside Void (instead of just performing a check to make sure they have the model). If anyone wants to look into this, feel free!

**Comment by andrewpareles** [comment]
#172 is the updated version of this.

We might want to let users pull models - that's now part of #165.
