### ISSUE TITLE
sent a message to Ollama without response

### ISSUE THREAD

**Issue by hubin858130** [voideditor/void#97]
I am sure that the ollama settings have been configured.
 I have already verified the same configuration.
However, after sending the message in VOID, no response was received,and the ollama server printed the following message:

[GIN] 2024/10/12 - 15:22:04 | 204 |      36.364µs |  61.155.154.152 | OPTIONS  "/api/chat"

204: HTTP status code
OPTIONS：HTTP request type

**Comment by andrewpareles** [comment]
Thanks for the report. Can you try again with the latest code? We recently made a lot of routing changes.

**Comment by hubin858130** [comment]
After updating the code, I found that I still can't connect to the Olama server and openAICompatible server properly.
I pulled the code using the following command:
_'git pull origin main'_
and then :
_'cd void/extensions/void',_
_'npm run build',_
and  ran with 'F5'.
**1. I set up my openAICompatible config and sent the content, but I haven't received a reply.**
The server printed info:
[GIN] 2024/10/16 - 10:14:38 | 204 |       18.29µs |  61.155.154.152 | OPTIONS  "/v1/chat/completions"
[GIN] 2024/10/16 - 10:14:39 | 204 |      19.269µs |  61.155.154.152 | OPTIONS  "/v1/chat/completions"
[GIN] 2024/10/16 - 10:14:40 | 204 |      14.646µs |  61.155.154.152 | OPTIONS  "/v1/chat/completions"

**2. I set up Ollama config and sent the content, but I haven't received a reply either.**
The server printed info:
[GIN] 2024/10/16 - 10:12:17 | 204 |      23.159µs |  61.155.154.152 | OPTIONS  "/api/chat"

I have modified the code related to Olama's model configuration in package.json,added my models:
 "void.ollama.model": {
          "type": "string",
          "default": "llama3.1",
          "description": "Ollama model to use.",
          "enum": [
            "qwen25coder:latest",
            "deepseek-v2.5:latest",
            "codegemma",
            "codegemma:2b",
            "codegemma:7b"
            .........
          ]
        },

**Comment by andrewpareles** [comment]
Thanks, this is useful. Do any errors show up in the Console? (you can view VSCode's console by pressing Ctrl+Shift+P and then enter 'Developer: Toggle Developer Tools').

**Comment by hubin858130** [comment]
> Thanks, this is useful. Do any errors show up in the Console? (you can view VSCode's console by pressing Ctrl+Shift+P and then enter 'Developer: Toggle Developer Tools').

<img width="847" alt="image" src="https://github.com/user-attachments/assets/d0d74b2d-2d07-4fb2-bdaa-f4a6ab88629c">
Is it a cross domain issue?

**Comment by andrewpareles** [comment]
It looks like https://aicoder.y5kfpt.com/ doesn't have `vscode-webview://` listed as an allowed origin. Just curious, how are you hosting https://aicoder.y5kfpt.com/? Is this something you can control, or are you using some kind of service to deploy it? 

One solution is `Access-Control-Allow-Origin: vscode-webview://*` to the response on your aicoder server to get it to work. Another solution is for Void to add a proxy so people don't have to do this (this is probably the better option...)

**Comment by hubin858130** [comment]
> It looks like https://aicoder.y5kfpt.com/ doesn't have `vscode-webview://` listed as an allowed origin. Just curious, how are you hosting https://aicoder.y5kfpt.com/? Is this something you can control, or are you using some kind of service to deploy it?
> 
> One solution is to add `Access-Control-Allow-Origin: vscode-webview://*` to the response on your aicoder server to get it to work. Another solution is for Void to add a proxy so people don't have to do this (this is probably the better option...)

😊😊😊😊I downloaded this service from GitHub：https://github.com/ollama/ollama/releases.

when I set the public server  of [deepseek](https://www.deepseek.com/):https://api.deepseek.com/chat/completions,still err:
<img width="676" alt="image" src="https://github.com/user-attachments/assets/c2065439-f7be-4207-833d-46b979cdb764">

**Comment by andrewpareles** [comment]
I think the error you're seeing with deepseek is just that you haven't paid them. 

I could be wrong, but it looks like the server you're running has a CORS error because it's routing packets to Ollama. Ollama has the right CORS settings applied, but the server itself doesn't. 

If you could add Access-Control-Allow-Origin: vscode-webview://* to the server itself, that might fix the problem.

**Comment by hubin858130** [comment]
> It looks like https://aicoder.y5kfpt.com/ doesn't have `vscode-webview://` listed as an allowed origin even though you added it to OLLAMA_ORIGINS. I wonder if this is because the server is routing calls to Ollama? Just curious, how are you hosting https://aicoder.y5kfpt.com/?

Thanks for your reply!
 https://aicoder.y5kfpt.com/  is a nginx server.   
I have set the conf of nginx,added webview://1rfc0or1ee4t2bqkqc5hsk9emo8cf9s090aklamj9du17b258qu8",but it still err:
<img width="673" alt="image" src="https://github.com/user-attachments/assets/e3a0d011-2fa7-417b-8ccd-a3e5f1c7a232">

Deepseek can now be used normally after I deposit money.

**Comment by andrewpareles** [comment]
Without more information it's hard to help, but it seems your still server isn't sending the correct CORS headers.
